version: '3.8'

services:
  vscode-tunnel:
    image: wenutu/vscode-tunnel-docker:latest
    container_name: vscode_tunnel
    environment:
      PROVIDER: github
      BUILD: stable # stable, insider
      MACHINE_NAME: vscode-tunnel-docker
    volumes:
      - ./workspace:/root/workspace
      - ./vscode_data:/root/.vscode-server
      - ./vscode_cli_data:/root/.vscode/cli
    restart: unless-stopped
