#!/bin/bash
# Selecting architecture variant
case $1 in
  amd64)
    VARIANT="alpine-x64"
    ;;
  arm64)
    VARIANT="alpine-arm64"
    ;;
  *)
    VARIANT="linux-armhf"
    ;;
esac

echo "Using build $2 and variant $VARIANT for download"

# Downloading and unpacking VSCode CLI
curl -sL "https://code.visualstudio.com/sha/download?build=$2&os=cli-$VARIANT" --output /tmp/vscode-cli.tar.gz && \
tar -xf /tmp/vscode-cli.tar.gz -C /usr/bin && \
rm /tmp/vscode-cli.tar.gz

# Handling potential code-insiders executable
if [ -f "/usr/bin/code-insiders" ]; then
    mv /usr/bin/code-insiders /usr/bin/code
fi
