#!/bin/bash
# Initializing and setting up VSCode Tunnel
PROVIDER=${PROVIDER:-"github"}
if [ "$PROVIDER" = "microsoft" ]; then
    code tunnel user login --provider microsoft
fi
code tunnel --accept-server-license-terms --disable-telemetry --name "${MACHINE_NAME}"
