name: Build and publish image

on:
  push:
    branches:
      - main
  release:
    types: [published]
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish image job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKENS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          tags: wenutu/vscode-remote-tunnels:latest, wenutu/vscode-remote-tunnels:1.0.0
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
