name: Docker Build and Push Multi-Arch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKENS }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .Dockerfile
        push: true
        tags: wenutu/vscode-tunnel:latest
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        build-args: VSCODE_VERSION=latest

    - name: Deploy (optional)
      run: echo "Deployment can be customized here"

