name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKENS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: .Dockerfile
        tags: wenutu/vscode-cli-tunnel:latest
        push: true
        build-args: VSCODE_VERSION=latest

    - name: Deploy (optional)
      run: echo "Deployment steps can be customized based on deployment needs"
